name: CI

on:
  push:
    branches: [release/v2]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Cache incremental builds
        uses: actions/cache@v3
        with:
          path: |
            lib/
            tsconfig.tsbuildinfo
          key: build-${{ github.head_ref }}-${{ github.sha }}
          restore-keys: |
            build-${{ github.head_ref }}-
            build-refs/heads/release/v2-

      - run: npm ci
      - run: npm pack --dry-run

      - name: Example/Parcel builds
        run: |
          npm ci
          npm run build
        working-directory: example

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Cache incremental builds
        uses: actions/cache@v3
        with:
          path: |
            .eslintcache
            test/unit/tsconfig.tsbuildinfo
          key: test-${{ github.head_ref }}-${{ github.sha }}
          restore-keys: |
            test-${{ github.head_ref }}-
            test-refs/heads/release/v2-

      - run: npm ci
      - run: npm run lint
      - run: npm test

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests
