name: Release
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm publish --tag previous
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
